from EDArvores import *

arvore = ArvoreBB()

print('Arvore atual:')
arvore.imprimir(1)
print('')
print('-'*30)
print('Qual a raiz ?', arvore.getRaiz())
print('O numero 10 está na arvore?', arvore.buscar(10))
arvore.inserir(20)
arvore.inserir(10)
arvore.inserir(12)
arvore.inserir(8)
arvore.inserir(25)
arvore.inserir(30)
arvore.inserir(22)
print('Arvore atual(Pre-ordem):')
arvore.imprimir(1)
print('')
print('-'*30)
print('Arvore atual(Em-ordem):')
arvore.imprimir(2)
print('')
print('-'*30)
print('Arvore atual(Pos-ordem):')
arvore.imprimir(3)
print('')
print('-'*30)
print('Qual a raiz ?', arvore.getRaiz())
print('O numero 10 está na arvore?', arvore.buscar(10))
print('O numero 31 está na arvore?', arvore.buscar(31))

